name: Docker Image CI

on:
  release:
    types: [published]

jobs:
  docker:
    name: push docker image to hub
    runs-on: ubuntu-latest
    steps:
      - name: check repository
        uses: actions/checkout@v4

      - name: login to docker registry
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      # - name: Build the Docker image
      #   run: docker build . --file Dockerfile --tag traefik-forwardauth-cloudflare-access:$(date +%s)

      - name: build and push docker image to registry
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: nihaopaul/forward-auth:latest
